/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkIndexRouteImport } from './routes/work/index'
import { Route as ArtIndexRouteImport } from './routes/art/index'
import { Route as WorkSavemycityRouteImport } from './routes/work/savemycity'
import { Route as WorkProsperaiRouteImport } from './routes/work/prosperai'
import { Route as WorkAitaskforceRouteImport } from './routes/work/aitaskforce'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkIndexRoute = WorkIndexRouteImport.update({
  id: '/work/',
  path: '/work/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtIndexRoute = ArtIndexRouteImport.update({
  id: '/art/',
  path: '/art/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkSavemycityRoute = WorkSavemycityRouteImport.update({
  id: '/work/savemycity',
  path: '/work/savemycity',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkProsperaiRoute = WorkProsperaiRouteImport.update({
  id: '/work/prosperai',
  path: '/work/prosperai',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkAitaskforceRoute = WorkAitaskforceRouteImport.update({
  id: '/work/aitaskforce',
  path: '/work/aitaskforce',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/work/aitaskforce': typeof WorkAitaskforceRoute
  '/work/prosperai': typeof WorkProsperaiRoute
  '/work/savemycity': typeof WorkSavemycityRoute
  '/art': typeof ArtIndexRoute
  '/work': typeof WorkIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/work/aitaskforce': typeof WorkAitaskforceRoute
  '/work/prosperai': typeof WorkProsperaiRoute
  '/work/savemycity': typeof WorkSavemycityRoute
  '/art': typeof ArtIndexRoute
  '/work': typeof WorkIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/work/aitaskforce': typeof WorkAitaskforceRoute
  '/work/prosperai': typeof WorkProsperaiRoute
  '/work/savemycity': typeof WorkSavemycityRoute
  '/art/': typeof ArtIndexRoute
  '/work/': typeof WorkIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/work/aitaskforce'
    | '/work/prosperai'
    | '/work/savemycity'
    | '/art'
    | '/work'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/work/aitaskforce'
    | '/work/prosperai'
    | '/work/savemycity'
    | '/art'
    | '/work'
  id:
    | '__root__'
    | '/'
    | '/work/aitaskforce'
    | '/work/prosperai'
    | '/work/savemycity'
    | '/art/'
    | '/work/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WorkAitaskforceRoute: typeof WorkAitaskforceRoute
  WorkProsperaiRoute: typeof WorkProsperaiRoute
  WorkSavemycityRoute: typeof WorkSavemycityRoute
  ArtIndexRoute: typeof ArtIndexRoute
  WorkIndexRoute: typeof WorkIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/': {
      id: '/work/'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof WorkIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/art/': {
      id: '/art/'
      path: '/art'
      fullPath: '/art'
      preLoaderRoute: typeof ArtIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/savemycity': {
      id: '/work/savemycity'
      path: '/work/savemycity'
      fullPath: '/work/savemycity'
      preLoaderRoute: typeof WorkSavemycityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/prosperai': {
      id: '/work/prosperai'
      path: '/work/prosperai'
      fullPath: '/work/prosperai'
      preLoaderRoute: typeof WorkProsperaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/aitaskforce': {
      id: '/work/aitaskforce'
      path: '/work/aitaskforce'
      fullPath: '/work/aitaskforce'
      preLoaderRoute: typeof WorkAitaskforceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WorkAitaskforceRoute: WorkAitaskforceRoute,
  WorkProsperaiRoute: WorkProsperaiRoute,
  WorkSavemycityRoute: WorkSavemycityRoute,
  ArtIndexRoute: ArtIndexRoute,
  WorkIndexRoute: WorkIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
