/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkIndexRouteImport } from './routes/work/index'
import { Route as WorkProsperaiRouteImport } from './routes/work/prosperai'
import { Route as WorkAitaskforceRouteImport } from './routes/work/aitaskforce'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkIndexRoute = WorkIndexRouteImport.update({
  id: '/work/',
  path: '/work/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkProsperaiRoute = WorkProsperaiRouteImport.update({
  id: '/work/prosperai',
  path: '/work/prosperai',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkAitaskforceRoute = WorkAitaskforceRouteImport.update({
  id: '/work/aitaskforce',
  path: '/work/aitaskforce',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/work/aitaskforce': typeof WorkAitaskforceRoute
  '/work/prosperai': typeof WorkProsperaiRoute
  '/work': typeof WorkIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/work/aitaskforce': typeof WorkAitaskforceRoute
  '/work/prosperai': typeof WorkProsperaiRoute
  '/work': typeof WorkIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/work/aitaskforce': typeof WorkAitaskforceRoute
  '/work/prosperai': typeof WorkProsperaiRoute
  '/work/': typeof WorkIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/work/aitaskforce' | '/work/prosperai' | '/work'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/work/aitaskforce' | '/work/prosperai' | '/work'
  id: '__root__' | '/' | '/work/aitaskforce' | '/work/prosperai' | '/work/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WorkAitaskforceRoute: typeof WorkAitaskforceRoute
  WorkProsperaiRoute: typeof WorkProsperaiRoute
  WorkIndexRoute: typeof WorkIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/': {
      id: '/work/'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof WorkIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/prosperai': {
      id: '/work/prosperai'
      path: '/work/prosperai'
      fullPath: '/work/prosperai'
      preLoaderRoute: typeof WorkProsperaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/aitaskforce': {
      id: '/work/aitaskforce'
      path: '/work/aitaskforce'
      fullPath: '/work/aitaskforce'
      preLoaderRoute: typeof WorkAitaskforceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WorkAitaskforceRoute: WorkAitaskforceRoute,
  WorkProsperaiRoute: WorkProsperaiRoute,
  WorkIndexRoute: WorkIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
